#  MPV - osc.conf
#  deus0ww - 2026-04-10

layout=topbar
icon_style=fluent
seekrangestyle=bar
seekrangeseparate=no
seekrangealpha=192

deadzonesize=0.9
vidscale=no
scalewindowed=0.75
scalefullscreen=0.75
boxalpha=160
hidetimeout=1000
fadeduration=0
tooltipborder=0
timetotal=yes
unicodeminus=yes

font_icon=Segoe UI Symbol
font_mono=Helvetica Neue

custom_button_1_content=⏲️
custom_button_1_mbtn_left_command=set speed 1
custom_button_1_mbtn_right_command=set speed 1
custom_button_1_wheel_up_command=add speed -0.1
custom_button_1_wheel_down_command=add speed 0.1
